### ISSUE TITLE
Create Existing Branch error not reported as such

### ISSUE THREAD

**Issue by StevenACoffman** [mritd/gitflow-toolkit#14]
Thanks for making cool stuff!

When you try to repeat creating the an existing branch [the git wrapper for createBranch](https://github.com/mritd/gitflow-toolkit/blob/master/git_wapper.go#L36-L42) will not report the error specifically.
```go
func createBranch(name string) error {
	err := repoCheck()
	if err != nil {
		return fmt.Errorf("the current directory is not a git repository")
	}
	return gitCommand(os.Stdout, []string{"checkout", "-b", name})
}
```

Perhaps the return from [`gitCommand`](https://github.com/mritd/gitflow-toolkit/blob/c855b52bcfde4cc60c9118d4dbc63190d3c7d57d/common.go#L85-L103) could capture the exit code (128) and return that as a more specific error:
```
if err := cmd.Run() ; err != nil {
    if exitError, ok := err.(*exec.ExitError); ok {
        if  exitError.ExitCode() == 128 {
            return fmt.Errorf("branch already exists: %w", exitError)
        }
        return exitError
    }
}
```

**Comment by mritd** [comment]
Can you provide specific execution commands？

An error message was generated on the terminal when repeatedly creating a branch in my test:
![2021-04-23 19 55 07](https://user-images.githubusercontent.com/13043245/115867753-0b6d4380-a46e-11eb-8588-a18920d4965f.gif)

**Comment by StevenACoffman** [comment]
Your steps work well.
```
git checkout main
git feat error_proint
git checkout main
git feat error_proint
```
If I attempted to re-create a feature branch when I was not already in that branch, gitflow-toolkit could fall back to a checkout of that existing branch.

Now that I think about it, that new behavior would add complexity, and maybe it's better to let people manually react to mistakes like this. Thanks!
