### ISSUE TITLE
git ci 交互时 退格删除键不好用

### ISSUE THREAD

**Issue by linuxsky** [mritd/gitflow-toolkit#15]
git ci 交互时 退格删除键不好用

**Comment by mritd** [comment]
请问是无法删除么？还是其他问题 @linuxsky

**Comment by mritd** [comment]
@linuxsky v2.1.0 已经 pre release，请尝试使用 v2.1.0 版本测试一下。

**Comment by mritd** [comment]
There has been no response for too long, close this issue.
Please reopen it if necessary.
