### ISSUE TITLE
gitflow-toolkit version not working

### ISSUE THREAD

**Issue by ysicing** [mritd/gitflow-toolkit#16]
貌似version没有作用
```
gitflow-toolkit -v
gitflow-toolkit version
```

**Comment by mritd** [comment]
重新发了一下 release 应该已经修复了

**Comment by mritd** [comment]
主命令现在还有待优化，因为安装时不想完全的复制自己(空间占用洁癖 哈哈哈)，所以现在是采用软连接的方式；

软连接在执行时首先会检测自己的文件名，然后执行特定的子命令；但是为了实现这个效果导致了在代码层 主命令 `--help` 不显示子命令了，目前所有的子命令(ln -s 后的文件名)可以从这里看到 https://github.com/mritd/gitflow-toolkit/blob/master/install.go#L178
