### ISSUE TITLE
does this tool not support for windows?

### ISSUE THREAD

**Issue by godcong** [mritd/gitflow-toolkit#18]
i got the fail message on windows
![image](https://user-images.githubusercontent.com/2727298/134874851-7edf3a8a-268b-495b-aabf-b5b2d1558963.png)

**Comment by mritd** [comment]
Sorry, the original terminal of windows is not currently supported.
Since windows is friendly enough for WSL integration, we only support WSL.

![image](https://user-images.githubusercontent.com/13043245/134876447-9f3a90aa-7aee-4fb1-a868-e468dc013071.png)
