### ISSUE TITLE
使用的时候发现安装这个会导致 git hooks 不会被执行

### ISSUE THREAD

**Issue by Allenxuxu** [mritd/gitflow-toolkit#21]

**Comment by mritd** [comment]
默认安装后 会调整用户的 hooks，该配置位于 `~/.gitconfig` 配置文件中，你可以手动更改文件关闭掉。
这个操作确实有问题，会没有提示状态下修改用户配置；后续我提供选项来控制，并保证 默认关闭状态；

**Comment by Allenxuxu** [comment]
> 默认安装后 会调整用户的 hooks，该配置位于 `~/.gitconfig` 配置文件中，你可以手动更改文件关闭掉。 这个操作确实有问题，会没有提示状态下修改用户配置；后续我提供选项来控制，并保证 默认关闭状态；

我如果删除 [core] hooksPath 配置，gitflow-toolkit 还能正常工作吗

**Comment by mritd** [comment]
可以正常工作，当时增加 hooks 只是为了有人防止手动 `git cimmit -m "xxxxx"` 提交，然后乱写 commit message；
hooks 实际上并不参与标准的应用执行逻辑。

**Comment by Allenxuxu** [comment]
> 可以正常工作，当时增加 hooks 只是为了有人防止手动 `git cimmit -m "xxxxx"` 提交，然后乱写 commit message； hooks 实际上并不参与标准的应用执行逻辑。

👌，感谢解答

**Comment by mritd** [comment]
@Allenxuxu `v2.1.3` 版本在安装时增加了 `--hook` 选项来安装 commit 钩子；默认情况下不进行安装了。
